symbol_width = 1
character_height = 9

"a" = '''
          
          
          
 $$$$$$\  
 \____$$\ 
 $$$$$$$ |
$$  __$$ |
\$$$$$$$ |
 \_______|
'''

"b" = '''
          
$$\       
$$ |      
$$$$$$$\  
$$  __$$\ 
$$ |  $$ |
$$ |  $$ |
$$$$$$$  |
\_______/ 
'''

"c" = '''
          
          
          
 $$$$$$$\ 
$$  _____|
$$ /      
$$ |      
\$$$$$$$\ 
 \_______|
'''

"d" = '''
          
      $$\ 
      $$ |
 $$$$$$$ |
$$  __$$ |
$$ /  $$ |
$$ |  $$ |
\$$$$$$$ |
 \_______|
'''

"e" = '''
          
          
          
 $$$$$$\  
$$  __$$\ 
$$$$$$$$ |
$$   ____|
\$$$$$$$\ 
 \_______|
'''

"f" = '''
          
 $$$$$$\  
$$  __$$\ 
$$ /  \__|
$$$$\     
$$  _|    
$$ |      
$$ |      
\__|      
'''

"g" = '''
 $$$$$$\  
$$  __$$\ 
$$ /  $$ |
$$ |  $$ |
\$$$$$$$ |
 \____$$ |
$$\   $$ |
\$$$$$$  |
 \______/
'''

"h" = '''
          
$$\       
$$ |      
$$$$$$$\  
$$  __$$\ 
$$ |  $$ |
$$ |  $$ |
$$ |  $$ |
\__|  \__|
'''

"i" = '''
    
$$\ 
\__|
$$\ 
$$ |
$$ |
$$ |
$$ |
\__|
'''

"j" = '''
      $$\ 
      \__|
      $$\ 
      $$ |
      $$ |
      $$ |
$$\   $$ |
\$$$$$$  |
 \______/ 
'''

"k" = '''
          
$$\       
$$ |      
$$ |  $$\ 
$$ | $$  |
$$$$$$  / 
$$  _$$<  
$$ | \$$\ 
\__|  \__|
'''

"l" = '''
    
$$\ 
$$ |
$$ |
$$ |
$$ |
$$ |
$$ |
\__|
'''

"m" = '''
              
              
$$$$$$\$$$$\  
$$  _$$  _$$\ 
$$ / $$ / $$ |
$$ | $$ | $$ |
$$ | $$ | $$ |
$$ | $$ | $$ |
\__| \__| \__|
'''

"n" = '''
          
          
          
$$$$$$$\  
$$  __$$\ 
$$ |  $$ |
$$ |  $$ |
$$ |  $$ |
\__|  \__|
'''

"o" = '''
          
          
          
 $$$$$$\  
$$  __$$\ 
$$ /  $$ |
$$ |  $$ |
\$$$$$$  |
 \______/ 
'''

"p" = '''
 $$$$$$\  
$$  __$$\ 
$$ /  $$ |
$$ |  $$ |
$$$$$$$  |
$$  ____/ 
$$ |      
$$ |      
\__|      
'''

"q" = '''
 $$$$$$\  
$$  __$$\ 
$$ /  $$ |
$$ |  $$ |
\$$$$$$$ |
 \____$$ |
      $$ |
      $$ |
      \__|
'''

"r" = '''
          
          
          
 $$$$$$\  
$$  __$$\ 
$$ |  \__|
$$ |      
$$ |      
\__|      
'''

"s" = '''
          
          
          
 $$$$$$$\ 
$$  _____|
\$$$$$$\  
 \____$$\ 
$$$$$$$  |
\_______/ 
'''

"t" = '''
          
  $$\     
  $$ |    
$$$$$$\   
\_$$  _|  
  $$ |    
  $$ |$$\ 
  \$$$$  |
   \____/ 
'''

"u" = '''
          
          
          
$$\   $$\ 
$$ |  $$ |
$$ |  $$ |
$$ |  $$ |
\$$$$$$  |
 \______/ 
'''

"v" = '''
           
           
           
$$\    $$\ 
\$$\  $$  |
 \$$\$$  / 
  \$$$  /  
   \$  /   
    \_/    
'''

"w" = '''
              
              
              
$$\  $$\  $$\ 
$$ | $$ | $$ |
$$ | $$ | $$ |
$$ | $$ | $$ |
\$$$$$\$$$$  |
 \_____\____/ 
'''

"x" = '''
          
          
          
$$\   $$\ 
\$$\ $$  |
 \$$$$  / 
 $$  $$<  
$$  /\$$\ 
\__/  \__|
'''

"y" = '''
$$\   $$\ 
$$ |  $$ |
$$ |  $$ |
$$ |  $$ |
\$$$$$$$ |
 \____$$ |
$$\   $$ |
\$$$$$$  |
 \______/ 
'''

"z" = '''
          
          
          
$$$$$$$$\ 
\____$$  |
  $$$$ _/ 
 $$  _/   
$$$$$$$$\ 
\________|
'''

" " = """
        
        
        
        
        
        
        
        
        
"""
