# The name of this `.toml` file is what the font will be called. 

# character_height: number of lines each character takes up, INCLUDING the empty line at the top.
# The empty line is the same width as the character and is required. It determines the character’s
# width, since Unicode/UTF-8 symbols may take multiple bytes while still appearing as one character.
# This also acts as padding between lines in a banner.
character_height = 7

# symbol_width: number of bytes each (special) symbol in your ASCII art occupies (in UTF-8).
# Required for scrolling banners. Without it, custom symbols may not render correctly.
# For the default font characters, this is 1 as there are no special characters.
# NOTE: Until a more robust and automatic method is implemented, symbols that vary in byte length
# will not appear properly.
symbol_width = 1

# Define ASCII art for any of the following characters.
# a b c d e f g h i j k l m n o p q r s t u v w x y z
# <space> 1 2 3 4 5 6 7 8 9 0 ! @ # $ % ^ & * ( )
# , . / ; ' [ ] \ - = ` < > ? : " { } | _ + ~

# Below is the default font art. Creating a full font can be tedious, so you may define only the
# characters you need. Any unassigned characters will automatically fall back to the default font.
# NOTE: If the custom font differs in character_height or symbol_width from the default font, lines
# may misalign.

"a" = '''
       
       
  __ _ 
 / _` |
| (_| |
 \__,_|
       
'''

"b" = '''
       
 _     
| |__  
| '_ \ 
| |_) |
|_.__/ 
       
'''

"c" = '''
      
      
  ___ 
 / __|
| (__ 
 \___|
      
'''

"d" = '''
       
     _ 
  __| |
 / _` |
| (_| |
 \__,_|
       
'''

"e" = '''
       
       
  ___  
 / _ \ 
|  __/ 
 \___| 
       
'''

"f" = '''
      
  __  
 / _| 
| |_  
|  _| 
|_|   
      
'''

"g" = '''
        
        
  __ _  
 / _` | 
| (_| | 
 \__, | 
 |___/  
'''

"h" = '''
       
 _     
| |__  
| '_ \ 
| | | |
|_| |_|
       
'''

"i" = '''
    
 _  
(_) 
| | 
| | 
|_| 
    
'''

"j" = '''
      
   _  
  (_) 
  | | 
  | | 
 _/ | 
|__/  
'''

"k" = '''
       
 _     
| | __ 
| |/ / 
|   <  
|_|\_\ 
       
'''

"l" = '''
    
 _  
| | 
| | 
| | 
|_| 
    
'''

"m" = '''
            
            
 _ __ ___   
| '_ ` _ \  
| | | | | | 
|_| |_| |_| 
            
'''

"n" = '''
        
        
 _ __   
| '_ \  
| | | | 
|_| |_| 
        
'''

"o" = '''
        
        
  ___   
 / _ \  
| (_) | 
 \___/  
        
'''

"p" = '''
        
        
 _ __   
| '_ \  
| |_) | 
| .__/  
|_|     
'''

"q" = '''
        
        
  __ _  
 / _` | 
| (_| | 
 \__, | 
    |_| 
'''

"r" = '''
       
       
 _ __  
| '__| 
| |    
|_|    
       
'''

"s" = '''
      
      
 ___  
/ __| 
\__ \ 
|___/ 
      
'''

"t" = '''
      
 _    
| |_  
| __| 
| |_  
 \__| 
      
'''

"u" = '''
        
        
 _   _  
| | | | 
| |_| | 
 \__,_| 
        
'''

"v" = '''
        
        
__   __ 
\ \ / / 
 \ V /  
  \_/   
        
'''

"w" = '''
           
           
__      __ 
\ \ /\ / / 
 \ V  V /  
  \_/\_/   
           
'''

"x" = '''
       
       
__  __ 
\ \/ / 
 >  <  
/_/\_\ 
       
'''

"y" = '''
        
        
 _   _  
| | | | 
| |_| | 
 \__, | 
 |___/  
'''

"z" = '''
      
      
 ____ 
|_  / 
 / /  
/___| 
      
'''

" " = '''
      
      
      
      
      
      
      
'''

"0" = '''
        
  ___   
 / _ \  
| | | | 
| |_| | 
 \___/  
        
'''

"1" = '''
    
 _  
/ | 
| | 
| | 
|_| 
    
'''

"2" = '''
        
 ____   
|___ \  
  __) | 
 / __/  
|_____| 
        
'''

"3" = '''
        
 _____  
|___ /  
  |_ \  
 ___) | 
|____/  
        
'''

"4" = '''
         
 _  _    
| || |   
| || |_  
|__   _| 
   |_|   
         
'''

"5" = '''
        
 ____   
| ___|  
|___ \  
 ___) | 
|____/  
        
'''

"6" = '''
        
  __    
 / /_   
| '_ \  
| (_) | 
 \___/  
        
'''

"7" = '''
        
 _____  
|___  | 
   / /  
  / /   
 /_/    
        
'''

"8" = '''
        
  ___   
 ( _ )  
 / _ \  
| (_) | 
 \___/  
        
'''

"9" = '''
        
  ___   
 / _ \  
| (_) | 
 \__, | 
   /_/  
        
'''

"," = '''
    
    
    
    
 _  
( ) 
|/  
'''

"." = '''
    
    
    
    
 _  
(_) 
    
'''

"/" = '''
       
    __ 
   / / 
  / /  
 / /   
/_/    
       
'''

";" = '''
    
    
 _  
(_) 
 _  
( ) 
|/  
'''

"'" = '''
    
 _  
( ) 
|/  
    
    
    
'''

"[" = '''
     
 __  
| _| 
| |  
| |  
| |  
|__| 
'''

"]" = '''
     
 __  
|_ | 
 | | 
 | | 
 | | 
|__| 
'''

"\\" = '''
       
__     
\ \    
 \ \   
  \ \  
   \_\ 
       
'''

"-" = '''
        
        
        
 _____  
|_____| 
        
        
'''

"=" = '''
        
        
 _____  
|_____| 
|_____| 
        
        
'''

"`" = '''
    
 _  
( ) 
 \| 
    
    
    
'''

"<" = '''
     
  __ 
 / / 
/ /  
\ \  
 \_\ 
     
'''

">" = '''
     
__   
\ \  
 \ \ 
 / / 
/_/  
     
'''

"?" = '''
      
 ___  
|__ \ 
  / / 
 |_|  
 (_)  
      
'''

":" = '''
    
    
 _  
(_) 
 _  
(_) 
    
'''

"\"" = '''
      
 _ _  
( | ) 
 V V  
      
      
      
'''

"{" = '''
      
   __ 
  / / 
 | |  
< <   
 | |  
  \_\ 
'''

"}" = '''
      
__    
\ \   
 | |  
  > > 
 | |  
/_/   
'''

"|" = '''
    
 _  
| | 
| | 
| | 
| | 
|_| 
'''

"_" = '''
        
        
        
        
        
 _____  
|_____| 
'''

"+" = '''
        
        
   _    
 _| |_  
|_   _| 
  |_|   
        
'''

"~" = '''
      
 /\/| 
|/\/  
      
      
      
      
'''

"!" = '''
    
 _  
| | 
| | 
|_| 
(_) 
    
'''

"@" = '''
          
   ____   
  / __ \  
 / / _` | 
| | (_| | 
 \ \__,_| 
  \____/  
'''

"#" = '''
           
   _  _    
 _| || |_  
|_  ..  _| 
|_      _| 
  |_||_|   
           
'''

"$" = '''
      
  _   
 | |  
/ __) 
\__ \ 
(   / 
 |_|  
'''

"%" = '''
       
 _  __ 
(_)/ / 
  / /  
 / /_  
/_/(_) 
       
'''

"^" = '''
     
 /\  
|/\| 
     
     
     
     
'''

"&" = '''
         
  ___    
 ( _ )   
 / _ \/\ 
| (_>  < 
 \___/\/ 
         
'''

"*" = '''
       
       
__/\__ 
\    / 
/_  _\ 
  \/   
       
'''

"(" = '''
     
  __ 
 / / 
| |  
| |  
| |  
 \_\ 
'''

")" = '''
     
__   
\ \  
 | | 
 | | 
 | | 
/_/  
'''

