# The name of this `.toml` file is what the font will be called. 

# character_height: number of lines each character takes up, INCLUDING the empty line at the top.
# The empty line is the same width as the character and is required. It determines the character’s
# width, since Unicode/UTF-8 symbols may take multiple bytes while still appearing as one character.
# This also acts as padding between lines in a banner.
character_height = 7

# symbol_width: number of bytes used to represent a single symbol in Unicode/UTF-8.
# Required for scrolling banners. Without it, custom symbols (like those in the default font) may
# not render correctly. For the default box-drawing characters, this is 3.
# NOTE: Until a more robust and automatic method is implemented, symbols that vary in byte length
# will not appear properly.
symbol_width = 3

# Below is the default font art. Creating a full font can be tedious, so you may define only the
# characters you need. Any unassigned characters will automatically fall back to the default font.
# NOTE: if the custom font differs in character_height from the default font, lines may misalign.

"a" = '''
        
 █████╗ 
██╔══██╗
███████║
██╔══██║
██║  ██║
╚═╝  ╚═╝
'''

"b" = '''
        
██████╗ 
██╔══██╗
██████╔╝
██╔══██╗
██████╔╝
╚═════╝ 
'''

"c" = '''
        
 ██████╗
██╔════╝
██║     
██║     
╚██████╗
 ╚═════╝
'''

"d" = '''
        
██████╗ 
██╔══██╗
██║  ██║
██║  ██║
██████╔╝
╚═════╝ 
'''

"e" = '''
        
███████╗
██╔════╝
█████╗  
██╔══╝  
███████╗
╚══════╝
'''

"f" = '''
        
███████╗
██╔════╝
█████╗  
██╔══╝  
██║     
╚═╝     
'''

"g" = '''
         
 ██████╗ 
██╔════╝ 
██║  ███╗
██║   ██║
╚██████╔╝
 ╚═════╝ 
'''

"h" = '''
        
██╗  ██╗
██║  ██║
███████║
██╔══██║
██║  ██║
╚═╝  ╚═╝
'''

"i" = '''
   
██╗
██║
██║
██║
██║
╚═╝
'''

"j" = '''
        
     ██╗
     ██║
     ██║
██   ██║
╚█████╔╝
 ╚════╝ 
'''

"k" = '''
        
██╗  ██╗
██║ ██╔╝
█████╔╝ 
██╔═██╗ 
██║  ██╗
╚═╝  ╚═╝
'''

"l" = '''
        
██╗     
██║     
██║     
██║     
███████╗
╚══════╝
'''

"m" = '''
           
███╗   ███╗
████╗ ████║
██╔████╔██║
██║╚██╔╝██║
██║ ╚═╝ ██║
╚═╝     ╚═╝
'''

"n" = '''
          
███╗   ██╗
████╗  ██║
██╔██╗ ██║
██║╚██╗██║
██║ ╚████║
╚═╝  ╚═══╝
'''

"o" = '''
         
 ██████╗ 
██╔═══██╗
██║   ██║
██║   ██║
╚██████╔╝
 ╚═════╝ 
'''

"p" = '''
        
██████╗ 
██╔══██╗
██████╔╝
██╔═══╝ 
██║     
╚═╝     
'''

"q" = '''
         
 ██████╗ 
██╔═══██╗
██║   ██║
██║▄▄ ██║
╚██████╔╝
 ╚══▀▀═╝ 
'''

"r" = '''
        
██████╗ 
██╔══██╗
██████╔╝
██╔══██╗
██║  ██║
╚═╝  ╚═╝
'''

"s" = '''
        
███████╗
██╔════╝
███████╗
╚════██║
███████║
╚══════╝
'''

"t" = '''
         
████████╗
╚══██╔══╝
   ██║   
   ██║   
   ██║   
   ╚═╝   
'''

"u" = '''
         
██╗   ██╗
██║   ██║
██║   ██║
██║   ██║
╚██████╔╝
 ╚═════╝ 
'''

"v" = '''
         
██╗   ██╗
██║   ██║
██║   ██║
╚██╗ ██╔╝
 ╚████╔╝ 
  ╚═══╝  
'''

"w" = '''
          
██╗    ██╗
██║    ██║
██║ █╗ ██║
██║███╗██║
╚███╔███╔╝
 ╚══╝╚══╝ 
'''

"x" = '''
        
██╗  ██╗
╚██╗██╔╝
 ╚███╔╝ 
 ██╔██╗ 
██╔╝ ██╗
╚═╝  ╚═╝
'''

"y" = '''
         
██╗   ██╗
╚██╗ ██╔╝
 ╚████╔╝ 
  ╚██╔╝  
   ██║   
   ╚═╝   
'''

"z" = '''
        
███████╗
╚══███╔╝
  ███╔╝ 
 ███╔╝  
███████╗
╚══════╝
'''

" " = '''
        
        
        
        
        
        
        
'''

"0" = '''
         
 ██████╗ 
██╔═████╗
██║██╔██║
████╔╝██║
╚██████╔╝
 ╚═════╝ 
'''

"1" = '''
    
 ██╗
███║
╚██║
 ██║
 ██║
 ╚═╝
'''

"2" = '''
        
██████╗ 
╚════██╗
 █████╔╝
██╔═══╝ 
███████╗
╚══════╝
'''

"3" = '''
        
██████╗ 
╚════██╗
 █████╔╝
 ╚═══██╗
██████╔╝
╚═════╝ 
'''

"4" = '''
        
██╗  ██╗
██║  ██║
███████║
╚════██║
     ██║
     ╚═╝
'''

"5" = '''
        
███████╗
██╔════╝
███████╗
╚════██║
███████║
╚══════╝
'''

"6" = '''
         
 ██████╗ 
██╔════╝ 
███████╗ 
██╔═══██╗
╚██████╔╝
 ╚═════╝ 
'''

"7" = '''
        
███████╗
╚════██║
    ██╔╝
   ██╔╝ 
   ██║  
   ╚═╝  
'''

"8" = '''
        
 █████╗ 
██╔══██╗
╚█████╔╝
██╔══██╗
╚█████╔╝
 ╚════╝ 
'''

"9" = '''
        
 █████╗ 
██╔══██╗
╚██████║
 ╚═══██║
 █████╔╝
 ╚════╝ 
'''

"," = '''
   
   
   
   
▄█╗
╚═╝
'''

"." = '''
   
   
   
   
██╗
╚═╝
'''

"/" = '''
       
    ██╗
   ██╔╝
  ██╔╝ 
 ██╔╝  
██╔╝   
╚═╝    
'''

";" = '''
   
██╗
╚═╝
▄█╗
▀═╝
   
'''

"'" = '''
   
██╗
██║
╚═╝
   
   
   
'''

"[" = '''
   
███╗
██╔╝
██║ 
██║ 
███╗
╚══╝
'''

"]" = '''
    
███╗
╚██║
 ██║
 ██║
███║
╚══╝
'''

"\\" = '''
       
██╗    
╚██╗   
 ╚██╗  
  ╚██╗ 
   ╚██╗
    ╚═╝
'''

"-" = '''
      
      
      
█████╗
╚════╝
      
      
'''

"=" = '''
       
       
██████╗
╚═════╝
██████╗
╚═════╝

'''

"`" = '''
    
██╗ 
╚██╗
 ╚═╝
   
   
   
'''

"<" = '''
     
  ██╗
 ██╔╝
██╔╝ 
╚██╗ 
 ╚██╗
  ╚═╝
'''

">" = '''
     
██╗  
╚██╗ 
 ╚██╗
 ██╔╝
██╔╝ 
╚═╝  
'''

"?" = '''
        
██████╗ 
╚════██╗
  ▄███╔╝
  ▀▀══╝ 
  ██╗   
  ╚═╝   
'''

":" = '''
   
   
██╗
╚═╝
██╗
╚═╝
   
'''

"\"" = '''
      
██╗██╗
██║██║
╚═╝╚═╝
      
      
      
'''

"{" = '''
   
  ██╗
 ██╔╝
███║  
╚██║  
 ╚██╗
  ╚═╝
'''

"}" = '''
   
██╗ 
╚██╗
 ███
 ██║
██╔╝
╚═╝ 
'''

"|" = '''
   
██╗
██║
██║
██║
██║
╚═╝
'''

"_" = '''
   
        
        
        
        
███████╗
╚══════╝
'''

"+" = '''
   
       
  ██╗  
██████╗
╚═██╔═╝
  ╚═╝  
       
'''

"~" = '''
   
        
        
▄███▄▄▄█
▀   ▀▀▀ 
        
        
'''

"!" = '''
   
██╗
██║
██║
╚═╝
██╗
╚═╝
'''

"@" = '''
        
 ██████╗ 
██╔═══██╗
██║██╗██║
██║██║██║
╚█║████╔╝
 ╚╝╚═══╝ 
'''

"#" = '''
   
 ██╗ ██╗ 
████████╗
╚██╔═██╔╝
████████╗
╚██╔═██╔╝
 ╚═╝ ╚═╝ 
'''

"$" = '''
   
▄▄███▄▄╗
██╔════╝
███████╗
╚════██║
███████║
╚═▀▀▀══╝
'''

"%" = '''
   
██╗ ██╗
╚═╝██╔╝
  ██╔╝ 
 ██╔╝  
██╔╝██╗
╚═╝ ╚═╝
'''

"^" = '''
   
 ███╗ 
██╔██╗
╚═╝╚═╝
      
      
      
'''

"&" = '''
   
   ██╗   
   ██║   
████████╗
██╔═██╔═╝
██████║  
╚═════╝  
'''

"*" = '''
   
      
▄ ██╗▄
 ████╗
▀╚██╔▀
  ╚═╝ 
      
'''

"(" = '''
   
 ██╗
██╔╝
██║  
██║  
╚██╗
 ╚═╝
'''

")" = '''
   
██╗ 
╚██╗
 ██║
 ██║
██╔╝
╚═╝ 
'''

